export const API_ERROR_CODES = [
  'VALIDATION_ERROR',
  'INVALID_CREDENTIALS',
  'UNAUTHENTICATED',
  'USER_INACTIVE',
  'FORBIDDEN',
  'FEATURE_NOT_ENABLED',
  'PERMISSION_DENIED',
  'FEATURE_PERMISSION_DENIED',
  'DESKTOP_LOGIN_FORBIDDEN',
  'DESKTOP_TOKEN_NOT_BOUND',
  'DESKTOP_TOKEN_DEVICE_MISMATCH',
  'DESKTOP_CONTEXT_REQUIRED',
  'DESKTOP_ACCESS_FORBIDDEN',
  'DESKTOP_SHIFT_ALREADY_OPEN',
  'DESKTOP_SHIFT_NOT_OPEN',
  'DESKTOP_SHIFT_ACCESS_DENIED',
  'DESKTOP_SHIFT_ALREADY_PAUSED',
  'DESKTOP_SHIFT_NOT_PAUSED',
  'DESKTOP_SHIFT_ACTIVE_PAUSE_NOT_FOUND',
  'NOT_FOUND',
  'ROUTE_NOT_FOUND',
  'MODEL_NOT_FOUND',
  'METHOD_NOT_ALLOWED',
  'TOO_MANY_REQUESTS',
  'CONFLICT',
  'IDEMPOTENCY_CONFLICT',
  'LOYALTY_FEATURE_NOT_ENABLED',
  'ACCOUNTING_FEATURE_NOT_ENABLED',
  'COMPANY_LIMIT_REACHED',
  'COMPANY_LAST_ADMIN',
  'SERVER_ERROR',
  'SERVICE_UNAVAILABLE'
] as const

export const UNKNOWN_API_ERROR_CODE = 'UNKNOWN' as const

export type KnownApiErrorCode = (typeof API_ERROR_CODES)[number]
export type ApiErrorCode = KnownApiErrorCode | typeof UNKNOWN_API_ERROR_CODE

export function isKnownApiErrorCode(code: string): code is KnownApiErrorCode {
  return (API_ERROR_CODES as readonly string[]).includes(code)
}

export function toApiErrorCode(code: string): ApiErrorCode {
  return isKnownApiErrorCode(code) ? code : UNKNOWN_API_ERROR_CODE
}
