import { equal, ok } from 'node:assert/strict'
import { randomUUID } from 'node:crypto'
import { databaseTest } from '../support/sandbox'
import {
  liveBackendScalar,
  liveHistoricalTrackStockBackendAvailable,
  liveUploadFixture,
  type HistoricalTrackStockContext
} from '../support/liveUploadBackend'
import { buildUploadPayload } from '../../../src/main/services/localSale.payload'
import type {
  LocalInvoiceItemRow,
  LocalInvoicePaymentRow,
  LocalInvoiceRow
} from '@shared/contracts/sale.contract'

const UPLOAD_PATH = '/api/v1/desktop/invoices/upload'

/**
 * PS9 — a v3 line frozen while its product was untracked, generated by the desktop's own payload
 * builder, uploaded AFTER the product became tracked on the server, and accepted by real Laravel
 * over real HTTP.
 *
 * This is the `POS-235a06-20260920-000003` incident executed rather than described. The seeder
 * (`ps7:seed-physical-presence-fixture`) creates the product untracked, issues its catalog
 * revision, THEN toggles it to tracked through the real `UpdateProductAction` — the same real
 * action that closes the evidence gap. The body sent here is not hand-written and not minted by
 * the seeder: it comes out of `buildUploadPayload()`, the same function the upload worker calls on
 * committed rows, using the FROZEN (pre-toggle) revision — proving real Electron output, generated
 * from a genuinely-untracked local snapshot, is accepted against a server where the product is now
 * tracked, with zero stock effects.
 *
 * Skips when no live backend was provided, so `npm run test:sqlite:electron` stays hermetic.
 */
function liveTest(name: string, callback: () => Promise<void>): void {
  databaseTest(name, async () => await callback(), {
    skip: liveHistoricalTrackStockBackendAvailable()
      ? false
      : 'no live PS9 historical-track-stock backend provided'
  })
}

async function upload(body: Record<string, unknown>): Promise<Response> {
  const fixture = liveUploadFixture()
  ok(fixture !== null)

  return fetch(new URL(UPLOAD_PATH, fixture.origin), {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${fixture.token}`,
      'X-Device-UUID': fixture.deviceUuid,
      'Content-Type': 'application/json',
      Accept: 'application/json'
    },
    body: JSON.stringify(body)
  })
}

// Read-only server-side counts go through the sanctioned support module: a suite must never open
// a database itself (`electronHarnessIntegrity.test.ts`).
const serverScalar = liveBackendScalar

/** A committed local invoice row, exactly as the checkout path would have written it. */
function committedInvoice(
  context: HistoricalTrackStockContext,
  localUuid: string,
  total: number
): LocalInvoiceRow {
  const fixture = liveUploadFixture()
  ok(fixture !== null)

  return {
    localUuid,
    attemptKey: randomUUID(),
    offlineNumber: `POS-235a06-20260920-${localUuid.slice(0, 6)}`,
    remoteUuid: null,
    serverNumber: null,
    syncStatus: 'pending',
    syncAttempts: 0,
    lastSyncError: null,
    syncedAt: null,
    companyUuid: fixture.companyUuid,
    branchUuid: randomUUID(),
    warehouseUuid: randomUUID(),
    deviceUuid: fixture.deviceUuid,
    userUuid: randomUUID(),
    shiftUuid: fixture.shiftUuid,
    commitSessionEpoch: 1,
    catalogRevision: context.catalog_revision,
    intentFingerprint: 'a'.repeat(64),
    customerUuid: null,
    currency: context.currency,
    currencyExponent: 2,
    taxMode: 'none',
    invoiceDiscountType: null,
    invoiceDiscountValue: 0,
    subtotalAmount: total,
    discountTotalAmount: 0,
    taxTotalAmount: 0,
    grandTotalAmount: total,
    paidTotalAmount: total,
    changeDueAmount: 0,
    dueAmount: 0,
    soldAt: context.sold_at,
    connectivityStateAtSale: 'offline',
    soldWhileOffline: true,
    notes: null,
    commercialSnapshotJson: '{}',
    uploadPayloadVersion: 1,
    // PS4: the presence of this is what selects the v3 shape, so the emitted version is a property
    // of the sale rather than of the uploader.
    offlineSaleAuthorityUuid: context.authority_uuid,
    createdAt: context.sold_at,
    updatedAt: context.sold_at
  } as LocalInvoiceRow
}

/**
 * The line as the DESKTOP actually committed it at the time of sale: `trackStock: false`, because
 * that was true then — the local snapshot correctly reflects the product's state AT SALE TIME,
 * never the server's current, since-mutated state.
 */
function committedItem(
  context: HistoricalTrackStockContext,
  invoiceLocalUuid: string,
  quantityMilli: number
): LocalInvoiceItemRow {
  const total = (context.unit_price_amount * quantityMilli) / 1000

  return {
    localUuid: randomUUID(),
    invoiceLocalUuid,
    lineIndex: 0,
    productUuid: context.product_uuid,
    productName: 'Historical Item',
    sku: 'PS-HISTORICAL',
    barcode: null,
    unit: null,
    trackStock: false,
    quantityMilli,
    unitPriceAmount: context.unit_price_amount,
    currency: context.currency,
    priceRevision: context.price_revision,
    taxUuid: context.tax_id,
    taxMode: 'none',
    taxRateBasisPoints: context.tax_rate_basis_points,
    taxRevision: context.tax_revision,
    discountType: null,
    discountValue: 0,
    subtotalAmount: total,
    discountAmount: 0,
    taxAmount: 0,
    totalAmount: total,
    allocationCoveredMilli: 0,
    uncoveredMilli: 0,
    createdAt: '2026-09-20T12:48:04.733Z'
  }
}

function committedPayment(
  context: HistoricalTrackStockContext,
  invoiceLocalUuid: string,
  amount: number
): LocalInvoicePaymentRow {
  return {
    localUuid: randomUUID(),
    invoiceLocalUuid,
    paymentIndex: 0,
    paymentMethodUuid: context.payment_method_uuid,
    type: 'cash',
    amount,
    reference: null,
    requiresReference: false,
    paidAt: context.sold_at,
    methodSnapshotJson: '{}',
    createdAt: '2026-09-20T12:48:04.733Z'
  }
}

liveTest(
  'PS9 a desktop-generated v3 line frozen untracked is accepted after the product becomes tracked on the server',
  async () => {
    const fixture = liveUploadFixture()
    ok(fixture !== null)

    const context = fixture.historicalTrackStockContext
    ok(context !== null)

    // Confirm the live server's premise before uploading: the product IS currently tracked there
    // — the seeder toggled it through the real action after issuing this frozen revision.
    equal(
      serverScalar(
        'SELECT COUNT(*) AS total FROM products WHERE uuid = ? AND track_stock = 1',
        context.product_uuid
      ),
      1
    )

    const localUuid = randomUUID()
    const amount = context.unit_price_amount
    const payload = buildUploadPayload(
      committedInvoice(context, localUuid, amount),
      [committedItem(context, localUuid, 1_000)],
      [committedPayment(context, localUuid, amount)],
      new Map(),
      new Map()
    )

    // The generator's own output: v3, and a line carrying NEITHER key — exactly the incident's
    // frozen shape, correct for what was true when the desktop committed this sale.
    equal(payload.client_contract_version, 3)
    const line = (payload.items as Record<string, unknown>[])[0]
    equal(Object.prototype.hasOwnProperty.call(line, 'stock_authorization'), false)
    equal(Object.prototype.hasOwnProperty.call(line, 'allocations'), false)

    const response = await upload(payload)

    equal(response.status, 201)

    const offlineNumber = payload.offline_number as string

    equal(
      serverScalar(
        'SELECT COUNT(*) AS total FROM pos_invoices WHERE offline_number = ?',
        offlineNumber
      ),
      1
    )
    // No stock movement, no allocation consumption, no stock item conjured — the CURRENTLY-tracked
    // product's ledger is untouched by a line proven untracked at sale time.
    equal(
      serverScalar(
        `SELECT COUNT(*) AS total FROM stock_movements m
           JOIN pos_invoices i ON i.id = m.pos_invoice_id
          WHERE i.offline_number = ?`,
        offlineNumber
      ),
      0
    )
    equal(
      serverScalar(
        'SELECT COUNT(*) AS total FROM stock_allocation_consumptions WHERE invoice_idempotency_key = ?',
        localUuid
      ),
      0
    )
    equal(
      serverScalar(
        `SELECT COUNT(*) AS total FROM stock_items s
           JOIN products p ON p.id = s.product_id
          WHERE p.uuid = ?`,
        context.product_uuid
      ),
      0
    )
  }
)

liveTest('PS9 an exact replay of the accepted historical sale writes nothing further', async () => {
  const fixture = liveUploadFixture()
  ok(fixture !== null)

  const context = fixture.historicalTrackStockContext
  ok(context !== null)

  const localUuid = randomUUID()
  const amount = context.unit_price_amount
  const payload = buildUploadPayload(
    committedInvoice(context, localUuid, amount),
    [committedItem(context, localUuid, 1_000)],
    [committedPayment(context, localUuid, amount)],
    new Map(),
    new Map()
  )

  equal((await upload(payload)).status, 201)

  const invoicesBefore = serverScalar('SELECT COUNT(*) AS total FROM pos_invoices')
  const movementsBefore = serverScalar('SELECT COUNT(*) AS total FROM stock_movements')

  // 200 duplicate, not 201.
  equal((await upload(payload)).status, 200)

  equal(serverScalar('SELECT COUNT(*) AS total FROM pos_invoices'), invoicesBefore)
  equal(serverScalar('SELECT COUNT(*) AS total FROM stock_movements'), movementsBefore)
  equal(
    serverScalar(
      'SELECT COUNT(*) AS total FROM desktop_invoice_syncs WHERE local_invoice_uuid = ?',
      localUuid
    ),
    1
  )
})
