import { equal, ok } from 'node:assert/strict'
import { randomUUID } from 'node:crypto'
import { databaseTest } from '../support/sandbox'
import {
  liveBackendScalar,
  liveServiceLineBackendAvailable,
  liveUploadFixture,
  type ServiceLineCatalogEntry,
  type ServiceLineContext
} from '../support/liveUploadBackend'
import { buildUploadPayload } from '../../../src/main/services/localSale.payload'
import type {
  LocalInvoiceItemRow,
  LocalInvoicePaymentRow,
  LocalInvoiceRow
} from '@shared/contracts/sale.contract'

const UPLOAD_PATH = '/api/v1/desktop/invoices/upload'

/**
 * PS8 — a v3 invoice carrying an **untracked service line**, generated by the desktop's own payload
 * builder and accepted by a real Laravel over real HTTP.
 *
 * This is the `POS-235a06-20260914-000003` incident executed rather than described. The body is not
 * hand-written here and not minted by the backend seeder: it comes out of `buildUploadPayload()`,
 * the same function the upload worker calls on committed rows, so what is proven is that real
 * Electron output is accepted — which a hand-authored body could never establish.
 *
 * Skips when no live backend was provided, so `npm run test:sqlite:electron` stays hermetic.
 */
function liveTest(name: string, callback: () => Promise<void>): void {
  databaseTest(name, async () => await callback(), {
    skip: liveServiceLineBackendAvailable() ? false : 'no live PS8 service-line backend provided'
  })
}

async function upload(body: Record<string, unknown>): Promise<Response> {
  const fixture = liveUploadFixture()
  ok(fixture !== null)

  return fetch(new URL(UPLOAD_PATH, fixture.origin), {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${fixture.token}`,
      'X-Device-UUID': fixture.deviceUuid,
      'Content-Type': 'application/json',
      Accept: 'application/json'
    },
    body: JSON.stringify(body)
  })
}

// Read-only server-side counts go through the sanctioned support module: a suite must never open
// a database itself (`electronHarnessIntegrity.test.ts`).
const serverScalar = liveBackendScalar

/** A committed local invoice row, exactly as the checkout path would have written it. */
function committedInvoice(
  context: ServiceLineContext,
  localUuid: string,
  total: number
): LocalInvoiceRow {
  const fixture = liveUploadFixture()
  ok(fixture !== null)

  return {
    localUuid,
    attemptKey: randomUUID(),
    offlineNumber: `POS-235a06-20260914-${localUuid.slice(0, 6)}`,
    remoteUuid: null,
    serverNumber: null,
    syncStatus: 'pending',
    syncAttempts: 0,
    lastSyncError: null,
    syncedAt: null,
    companyUuid: fixture.companyUuid,
    branchUuid: randomUUID(),
    warehouseUuid: randomUUID(),
    deviceUuid: fixture.deviceUuid,
    userUuid: randomUUID(),
    shiftUuid: fixture.shiftUuid,
    commitSessionEpoch: 1,
    catalogRevision: context.catalog_revision,
    intentFingerprint: 'a'.repeat(64),
    customerUuid: null,
    currency: context.currency,
    currencyExponent: 2,
    taxMode: 'none',
    invoiceDiscountType: null,
    invoiceDiscountValue: 0,
    subtotalAmount: total,
    discountTotalAmount: 0,
    taxTotalAmount: 0,
    grandTotalAmount: total,
    paidTotalAmount: total,
    changeDueAmount: 0,
    dueAmount: 0,
    soldAt: context.sold_at,
    connectivityStateAtSale: 'offline',
    soldWhileOffline: true,
    notes: null,
    commercialSnapshotJson: '{}',
    uploadPayloadVersion: 1,
    // PS4: the presence of this is what selects the v3 shape, so the emitted version is a property
    // of the sale rather than of the uploader.
    offlineSaleAuthorityUuid: context.authority_uuid,
    createdAt: context.sold_at,
    updatedAt: context.sold_at
  } as LocalInvoiceRow
}

function committedItem(
  entry: ServiceLineCatalogEntry,
  invoiceLocalUuid: string,
  options: {
    readonly lineIndex: number
    readonly trackStock: boolean
    readonly quantityMilli: number
    readonly currency: string
    readonly coveredMilli?: number
  }
): LocalInvoiceItemRow {
  const total = (entry.unit_price_amount * options.quantityMilli) / 1000
  const covered = options.coveredMilli ?? 0

  return {
    localUuid: randomUUID(),
    invoiceLocalUuid,
    lineIndex: options.lineIndex,
    productUuid: entry.product_uuid,
    productName: options.trackStock ? 'Tracked Item' : 'Service Item',
    sku: options.trackStock ? null : 'PS-SERVICE',
    barcode: options.trackStock ? null : '2000000000039',
    unit: null,
    trackStock: options.trackStock,
    quantityMilli: options.quantityMilli,
    unitPriceAmount: entry.unit_price_amount,
    currency: options.currency,
    priceRevision: entry.price_revision,
    taxUuid: entry.tax_id,
    taxMode: 'none',
    taxRateBasisPoints: entry.tax_rate_basis_points,
    taxRevision: entry.tax_revision,
    discountType: null,
    discountValue: 0,
    subtotalAmount: total,
    discountAmount: 0,
    taxAmount: 0,
    totalAmount: total,
    allocationCoveredMilli: options.trackStock ? covered : 0,
    uncoveredMilli: options.trackStock ? options.quantityMilli - covered : 0,
    createdAt: '2026-09-14T12:32:04.733Z'
  }
}

function committedPayment(
  context: ServiceLineContext,
  invoiceLocalUuid: string,
  amount: number
): LocalInvoicePaymentRow {
  return {
    localUuid: randomUUID(),
    invoiceLocalUuid,
    paymentIndex: 0,
    paymentMethodUuid: context.payment_method_uuid,
    type: 'cash',
    amount,
    reference: null,
    requiresReference: false,
    paidAt: context.sold_at,
    methodSnapshotJson: '{}',
    createdAt: '2026-09-14T12:32:04.733Z'
  }
}

liveTest(
  'PS8 a desktop-generated v3 service-line payload is accepted by real Laravel and moves no stock',
  async () => {
    const fixture = liveUploadFixture()
    ok(fixture !== null)

    const context = fixture.serviceLineContext
    ok(context !== null)

    const localUuid = randomUUID()
    const amount = context.service.unit_price_amount
    const payload = buildUploadPayload(
      committedInvoice(context, localUuid, amount),
      [
        committedItem(context.service, localUuid, {
          lineIndex: 0,
          trackStock: false,
          quantityMilli: 1_000,
          currency: context.currency
        })
      ],
      [committedPayment(context, localUuid, amount)],
      new Map(),
      new Map()
    )

    // The generator's own output is the incident's shape: v3, and a line carrying NEITHER key.
    equal(payload.client_contract_version, 3)
    const line = (payload.items as Record<string, unknown>[])[0]
    equal(Object.prototype.hasOwnProperty.call(line, 'stock_authorization'), false)
    equal(Object.prototype.hasOwnProperty.call(line, 'allocations'), false)

    const response = await upload(payload)

    equal(response.status, 201)

    const offlineNumber = payload.offline_number as string

    equal(
      serverScalar(
        'SELECT COUNT(*) AS total FROM pos_invoices WHERE offline_number = ?',
        offlineNumber
      ),
      1
    )
    // A service touches no ledger: no movement, no consumption, and no stock item conjured for it.
    equal(
      serverScalar(
        `SELECT COUNT(*) AS total FROM stock_movements m
           JOIN pos_invoices i ON i.id = m.pos_invoice_id
          WHERE i.offline_number = ?`,
        offlineNumber
      ),
      0
    )
    equal(
      serverScalar(
        'SELECT COUNT(*) AS total FROM stock_allocation_consumptions WHERE invoice_idempotency_key = ?',
        localUuid
      ),
      0
    )
    equal(
      serverScalar(
        `SELECT COUNT(*) AS total FROM stock_items s
           JOIN products p ON p.id = s.product_id
          WHERE p.uuid = ?`,
        context.service.product_uuid
      ),
      0
    )
  }
)

liveTest('PS8 an exact replay of the service sale writes nothing further', async () => {
  // The recovery case: the same frozen bytes, re-offered under the same idempotency key, resolve to
  // the committed invoice instead of creating a second one.
  const fixture = liveUploadFixture()
  ok(fixture !== null)

  const context = fixture.serviceLineContext
  ok(context !== null)

  const localUuid = randomUUID()
  const amount = context.service.unit_price_amount
  const payload = buildUploadPayload(
    committedInvoice(context, localUuid, amount),
    [
      committedItem(context.service, localUuid, {
        lineIndex: 0,
        trackStock: false,
        quantityMilli: 1_000,
        currency: context.currency
      })
    ],
    [committedPayment(context, localUuid, amount)],
    new Map(),
    new Map()
  )

  equal((await upload(payload)).status, 201)

  const invoicesBefore = serverScalar('SELECT COUNT(*) AS total FROM pos_invoices')
  const paymentsBefore = serverScalar('SELECT COUNT(*) AS total FROM pos_payments')
  const movementsBefore = serverScalar('SELECT COUNT(*) AS total FROM stock_movements')

  // 200 duplicate, not 201.
  equal((await upload(payload)).status, 200)

  equal(serverScalar('SELECT COUNT(*) AS total FROM pos_invoices'), invoicesBefore)
  equal(serverScalar('SELECT COUNT(*) AS total FROM pos_payments'), paymentsBefore)
  equal(serverScalar('SELECT COUNT(*) AS total FROM stock_movements'), movementsBefore)
  equal(
    serverScalar(
      'SELECT COUNT(*) AS total FROM desktop_invoice_syncs WHERE local_invoice_uuid = ?',
      localUuid
    ),
    1
  )
})

liveTest(
  'PS8 a mixed tracked/untracked v3 payload settles each line on its own terms',
  async () => {
    const fixture = liveUploadFixture()
    ok(fixture !== null)

    const context = fixture.serviceLineContext
    ok(context !== null)

    const localUuid = randomUUID()
    const amount = context.tracked.unit_price_amount + context.service.unit_price_amount
    const payload = buildUploadPayload(
      committedInvoice(context, localUuid, amount),
      [
        // Tracked, held no grant: a genuine physical-presence deduction, declared as such.
        committedItem(context.tracked, localUuid, {
          lineIndex: 0,
          trackStock: true,
          quantityMilli: 1_000,
          currency: context.currency
        }),
        committedItem(context.service, localUuid, {
          lineIndex: 1,
          trackStock: false,
          quantityMilli: 1_000,
          currency: context.currency
        })
      ],
      [committedPayment(context, localUuid, amount)],
      new Map(),
      new Map()
    )

    const items = payload.items as Record<string, unknown>[]

    equal(items[0].stock_authorization, 'physical_presence')
    equal(Object.prototype.hasOwnProperty.call(items[1], 'stock_authorization'), false)

    equal((await upload(payload)).status, 201)

    const offlineNumber = payload.offline_number as string

    // Exactly one movement for the two-line invoice, and it belongs to the tracked product.
    equal(
      serverScalar(
        `SELECT COUNT(*) AS total FROM stock_movements m
         JOIN pos_invoices i ON i.id = m.pos_invoice_id
        WHERE i.offline_number = ?`,
        offlineNumber
      ),
      1
    )
    equal(
      serverScalar(
        `SELECT COUNT(*) AS total FROM stock_movements m
         JOIN pos_invoices i ON i.id = m.pos_invoice_id
         JOIN products p ON p.id = m.product_id
        WHERE i.offline_number = ? AND p.uuid = ? AND m.stock_authorization = 'physical_presence'`,
        offlineNumber,
        context.tracked.product_uuid
      ),
      1
    )
    equal(
      serverScalar(
        `SELECT COUNT(*) AS total FROM pos_invoice_items it
         JOIN pos_invoices i ON i.id = it.pos_invoice_id
        WHERE i.offline_number = ?`,
        offlineNumber
      ),
      2
    )
  }
)
